on:
  issue_comment:
    types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  GITHUB_CONTEXT: "${{ toJson(github) }}"
  EVENTS: "${{ toJson(github.event) }}"
  HTML_URL: "${{ toJson(github.event.issue.pull_request.html_url) }}"
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
#       - name: "get pullrequest url"
#         run: echo "$HTML_URL"
      - name: "get pullrequest"
        run: echo "${{ github.event.pull_request }}"
      - name: "echo upstream branch"
        run: "echo ${{ steps.upstreambranch.outputs.branchname }}\n"
      - name: Checkout Pull Request
        run: echo "${{github.event.number}}"
      - name: "echo Comment"
        run: echo "${{ github.event.comment.body }}\n"
#       - name: html_url
#         run: 'echo "$GITHUB_CONTEXT.event"'
      - name: Issue Comment
        uses: kentaro-m/add-an-issue-reference-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-prefix: "TICKET-"
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
            issue_number: github.event.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Hello World',
            })
